#!/bin/bash

case $button in
	1|2|3) pamixer --toggle-mute;;
	4) pamixer --increase 2;;
	5) pamixer --decrease 2;;
esac

mute=$(pamixer --get-mute)
[ "$mute" == "true" ] && echo "婢 " && exit 0

echo "墳 $(pamixer --get-volume)%"
exit 0
