#!/bin/bash

case $button in
	1|2|3) amixer -q sset Master toggle;;
	4) pactl set-sink-volume @DEFAULT_SINK@ '+2%';;
	5) pactl set-sink-volume @DEFAULT_SINK@ '-2%';;
esac

mute=$(amixer sget Master | grep -m1 -oP "(\[off\])|(\[on\])")
[ "$mute" == "[off]" ] && echo "婢 " && exit 0

echo "墳 $(amixer sget Master | grep -m1 -oP "\d+%")"
exit 0