#!/bin/bash

case $button in
	1|2|3) pamixer --toggle-mute;;
	4) pamixer --increase 2;;
	5) pamixer --decrease 2;;
esac

mute=$(pamixer --get-mute)
# nf-cod-mute
[ "$mute" == "true" ] && echo " " && exit 0

# nf-cod-unmute
echo " $(pamixer --get-volume)%"
exit 0
