#!/bin/sh

case $button in
	1) gammastep -O 5500 > /dev/null &;;
	2) $HOME/scripts/power-thing off;;
	3) killall gammastep > /dev/null;;
	4) light -A 2 > /dev/null;;
	5) light -U 2 > /dev/null;;
esac

# nf-oct-sun
printf ' %.f\n' "$(light -G)"
exit 0
