#!/bin/sh

case $button in
	1) gammastep -O 3000 > /dev/null &;;
	2) $HOME/scripts/power-thing off;;
	3) killall gammastep > /dev/null;;
	4) light -A 2 > /dev/null;;
	5) light -U 2 > /dev/null;;
esac

printf '盛 %.f\n' "$(light -G)"
exit 0
