#!/bin/sh

# stolen from
# https://github.com/vivien/i3blocks-contrib/blob/master/bandwidth/bandwidth
function format () {
	# return if negative
	[ $1 -lt 0 ] && echo -n "0B" && return

	# 1000 kib = 1024^1 * 1000 b
	# 1000 mib = 1024^2 * 1000 b
	# 1000 gib = 1024^3 * 1000 b
	# 1000 tib = 1024^4 * 1000 b
	
	# truncate to 3 digits
	if [[ $1 -lt 1000 ]]; then
		echo -n "${1}B"
	elif [[ $1 -lt 1024000 ]]; then
		echo -n "$(($1 >> 10))K"
	elif [[ $1 -lt 1048576000 ]]; then
		echo -n "$(($1 >> 20))M"
	elif [[ $1 -lt 1073741824000 ]]; then
		echo -n "$(($1 >> 30))G"
	else
		echo -n "$(($1 >> 40))T"
	fi
}

# check and pick interface
w=$(ls /sys/class/net/ | grep wlp)
e=$(ls /sys/class/net/ | grep enp)
if [ -e /sys/class/net/$e/operstate ] && \
	[ $(cat /sys/class/net/$e/operstate) = "up" ]
then
	interface=$e
elif [ -e /sys/class/net/$w/operstate ] && \
	[ $(cat /sys/class/net/$w/operstate) = "up" ]
then
	interface=$w
else
	echo ":("
	echo
	echo "#FF0000"
	exit 0
fi

# read current data
read rx < /sys/class/net/$interface/statistics/rx_bytes
read tx < /sys/class/net/$interface/statistics/tx_bytes
time=$(date +%s)

# check existance of past data
data=$XDG_CONFIG_HOME/i3blocks/network
[ -f $data ] || echo "$time $rx $tx" > $data && chmod u+rw $data

# parse past data
read -a old < $data
echo "$time $rx $tx" > $data
time=$(( $time - ${old[0]} ))
[ $time -le 0 ] && echo " 0B 祝 0B" && exit 0

# bytes/s
rx=$(( $rx - ${old[1]} ))
tx=$(( $tx - ${old[2]} ))
rx_rate=$(( $rx / $time ))
tx_rate=$(( $tx / $time ))

# print
echo -n " "
format $rx_rate
echo -n " 祝 "
format $tx_rate
echo

exit 0
