#!/bin/sh
vblank_mode=0 WINEARCH=win32 WINEPREFIX=$HOME/wine/osu-wine wine /mnt/d/pog/osu/osu\!.exe "$@"
# vblank_mode=0 WINEARCH=win32 WINEPREFIX=$HOME/wine/osu-wine wine /mnt/e/osu/osu\!/osu\!.exe "$@"
