#!/bin/bash
lock() {
	# https://www.reddit.com/r/unixporn/comments/pbm6qy/sway_first_time_ricing_on_linux_how_did_i_do/
	# https://github.com/shaunsingh/nix-darwin-dotfiles/tree/e900a178f3f379cd8b6f88abbe0bf75531909fd2/.config/scripts
	pgrep swaylock
	if [[ $? -eq 1 ]]; then
		swaymsg -q output DP-4 disable
		swaylock
	fi
}

off() {
	# TODO: maybe start swayidle and record pid then sigusr1 it ?
	# or wait for wayland updates lollllllll
	#sleep 0.3 && pkill -SIGUSR1 swayidle
	#swaymsg "output * dpms off"
	true
}

quiet=$([[ "$1" == "-q" ]] && echo 1 || echo 0)
[[ $quiet -ne 0 ]] && shift

case "$1" in
	nvm)
		;;
	on)
		swaymsg 'output * enable'
		;;
	off)
		off
		;;
	lock)
		lock
		;;
	exit)
		swaymsg exit
		;;
	suspend)
		lock; off && systemctl suspend
		;;
	hybrid-sleep)
		lock; off && systemctl hybrid-sleep
		;;
	hibernate)
		lock; off && systemctl hibernate
		;;
	reboot)
		systemctl reboot
		;;
	shutdown)
		systemctl poweroff
		;;
	*)
		[[ $quiet -ne 0 ]] && exit 0
		echo "Usage: $HOME/scripts/power-thing {on|off|lock|logout|suspend|hibrid-sleep|hibernate|reboot|shutdown}"
esac

exit 0
