#!/bin/bash
lock() {
    none=00000000   #000000
    wh=FFFFFFFF     #FFFFFF
    verif=00FFFFFF  #00FFFF
    wrong=FF0000FF  #FF0000
    key=00FF00FF    #00FF00
    back=FF0000FF   #FF0000

	i3lock -ei $HOME/.config/i3/year-of-the-linux-desktop.png \
    --pass-media-keys --pass-screen-keys --pass-power-keys \
    --time-align 2 --date-align 2 --greeter-align 2 \
    \
    --verif-text="" --wrong-text="" --noinput-text="" --lock-text="" --lockfailed-text="" \
    \
    --insidever-color=$verif --insidewrong-color=$wrong --inside-color=$none \
    --ringver-color=$wh --ringwrong-color=$wh --ring-color=$wh \
    --line-color=$none --separator-color=$wh \
    --keyhl-color=$key --bshl-color=$back \
    --indicator --radius 30 --ring-width 10 --ind-pos="10*r:h-4*r" \
    \
    --force-clock --time-font=hack --time-size=30 --date-font=hack --date-size=30 \
    --date-color=$wh --date-str="%a, %d %b" --date-pos="tx:ty-4*r/3" \
    --time-color=$wh --time-str="%I:%M:%S %p" --time-pos="ix-2*r:iy+r/4" \
    \
    --greeter-color=C1ACD3FF --greeter-size=20 --greeter-text="uwu" --greeter-pos="tx:ty+r"
}

quiet=$([[ "$1" == "-q" ]] && echo 1 || echo 0)
[[ $quiet -ne 0 ]] && shift

case "$1" in
    nvm)
        ;;
    on)
        xset dpms force on
        ;;
    off)
        xset dpms force off 
        ;;
	lock)
		lock && xset dpms force off
		;;
	exit)
		i3-msg exit
		;;
	suspend)
        lock && xset dpms force off && systemctl suspend
        ;;
    hibernate)
        lock && xset dpms force off && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        [[ $quiet -ne 0 ]] && exit 0
        echo "Usage: $HOME/scripts/power-thing {on|off|lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 1
esac

exit 0
