#!/bin/bash

case $button in
	1|2|3|4|5) swaymsg -q "exec scratchpad-menu";;
esac

# inspired by u/lightningshivam
# https://www.reddit.com/r/i3wm/comments/gdynp6/show_indicator_forcontent_of_scratchpad_on_status/fplc3gb
#windows=$(swaymsg -t get_tree | jq -r '.nodes | .[] | .nodes | .[] | select(.name=="__i3_scratch") | .floating_nodes | .[] | (.id | tostring) + "\t" + (.name | tostring)')

# efficiency improvement
windows=$(swaymsg -t get_tree | jq -r '.nodes | .[] | select(.name=="__i3") | .nodes | .[] | select(.name=="__i3_scratch") | .floating_nodes | .[] | .id')

# nf-cod-multiple_windows
echo -n " "
[[ -z "$windows" ]] && echo "0" && exit 0

count=$(wc -l <<< "$windows")
[[ count -ge 100 ]] && echo "**" || echo $count

exit 0
