#!/bin/bash
if [[ $# -ne 1 || $1 == '-h' || $1 == '--help' ]]; then
	echo "usage: $0 <host>"
	exit 1
fi

HOST="$@"

# reference: https://www.golinuxcloud.com/test-ssh-connection/
timeout --foreground --kill-after=3 5 \
	ssh -q \
	-o BatchMode=yes \
	-o StrictHostKeyChecking=no \
	-o ConnectTimeout=3 \
	$HOST 'exit 0'

STATUS="$?"
echo $STATUS
exit $STATUS
