#!/bin/bash
if [[ $1 == '-h' || $1 == '--help' ]]; then
	echo "usage: $0 dh20## pc## args?"
	exit 0
fi

DH=10
PC=48
ARGS=$@

if [[ $# -ge 2 ]]; then
	DH=$1
	PC=$2
	ARGS=${@:3}
fi

HOST="dh20${DH}pc${PC}"

if [[ $(ssh-check-connection "$HOST") -ne 0 ]]; then
	echo "$HOST is down"
	exit 1
fi

TERM=xterm ssh "$HOST" $ARGS
