#!/bin/bash
if [[ $1 == '-h' || $1 == '--help' ]]; then
	echo "usage: $0 dh# pc# args?"
	exit 0
fi

dh=2010
pc=07
args="$@"

if [[ $# -ge 2 ]]; then
	dh=$1
	pc=$2
	args="${@:3}"
fi

TERM=xterm ssh dh${dh}pc${pc} ${args}
