#!/bin/bash
if [[ $1 == '-h' || $1 == '--help' ]]; then
	echo "usage: $0 dh# pc# args?"
	exit 0
fi

DH=2010
PC=44
ARGS="$@"

if [[ $# -ge 2 ]]; then
	DH=$1
	PC=$2
	ARGS="${@:3}"
fi

HOST="dh${DH}pc${PC}"

if [[ $(ssh-check-connection "$HOST") -ne 0 ]]; then
	echo "$HOST is down"
	exit 1
fi

TERM=xterm ssh "$HOST" "$ARGS"
